apiVersion: batch/v1
kind: Job
metadata:
  name: spring-batch
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: error-batch
        image: sejoung/batch:0.1
      restartPolicy: Never
